---
- name: Install Ruby and Bundler
  hosts: all
  become_method: 'sudo'

  tasks:
  - name: Install ruby and rubygems
    apt: 
      name: "{{ item }}"
    vars:
      item:
      - ruby-full
      - ruby-bundler
      - build-essential
