---
- name: Install Ruby and Bundler
  hosts: all
  gather_facts: no
  become: true
  tasks:
  - name: Install ruby and rubygems
    apt: 
      name: "{{ item }}"
      state: present
    vars:
      item:
      - ruby-full
      - ruby-bundler
      - build-essential
